version: '3.8'

services:
  genti:
    image: byeongryeol/genti-dev:latest
    container_name: genti-dev
    volumes:
      - /home/ubuntu/workspace/logs:/logs # 로그 경로 마운트
    ports:
      - ${SERVER_BINDING_PORT}:${SERVER_CONTAINER_PORT}
  redis:
    image: redis:7.2.4
    container_name: redis-dev
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_CONTAINER_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
