FROM openjdk:21-jdk as builder

WORKDIR application
ARG JAR_FILE=genti-api/build/libs/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:21-jdk

WORKDIR application
ENV port 8080
EXPOSE 8080
ENV spring.profiles.active deploy

# build stage에 있는 파일을 복사
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./

COPY genti-api/src/main/resources/logback-spring.xml /application/
COPY genti-api/src/main/resources/console-appender.xml /application/
COPY genti-api/src/main/resources/discord-appender.xml /application/
COPY genti-api/src/main/resources/file-appender.xml /application/

ENTRYPOINT ["java", "-Dspring.profiles.active=deploy", "org.springframework.boot.loader.launch.JarLauncher"]